[project]
name = "gn-module-conservation-flora-exsitu"
description = "GeoNature module for conservation flora exsitu."
readme = "README.md"
requires-python = ">=3.11"
keywords = ["conservation", "flora", "exsitu"]
license = { file = "LICENSE.txt" }
maintainers = [
    { name = "Conservatoire Botanique National Alpin", email = "geonature@cbn-alpin.fr" },
]
authors = [
    { name = "Ahmadou Bassirou DIALLO", email = "ab.diallo@cbn-alpin.fr" },
    { name = "Cendrine HOARAU", email = "c.hoarau@cbn-alpin.fr" },
    { name = "Jean-Pascal MILCENT", email = "jp.milcent@cbn-alpin.fr" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
]
urls.homepage = "https://github.com/cbn-alpin/gn_module_conservation_flora_exsitu"
urls.documentation = "https://github.com/cbn-alpin/gn_module_conservation_flora_exsitu"
urls.repository = "https://github.com/cbn-alpin/gn_module_conservation_flora_exsitu"
dynamic = ["version"]
dependencies = ["geonature>=2.14.2"]

[project.optional-dependencies]
dev = [
    "ruff",
    # Manually install gn_conservation_backend_shared with `pip install -e <path-to-gn-conservation-backend-shared>` if not installed in venv
]

[project.entry-points.gn_module]
code = "gn_module_conservation_flora_exsitu:MODULE_CODE"
picto = "gn_module_conservation_flora_exsitu:MODULE_PICTO"
blueprint = "gn_module_conservation_flora_exsitu.blueprint:blueprint"
config_schema = "gn_module_conservation_flora_exsitu.conf_schema_toml:GnModuleSchemaConf"
migrations = "gn_module_conservation_flora_exsitu:migrations"
alembic_branch = "gn_module_conservation_flora_exsitu:MODULE_DB_BRANCH"

[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools>=60.0.0", "wheel"] # PEP 508 specifications.
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = { file = "VERSION" }

[tool.setuptools.packages.find]
where = ["backend"]
include = ["gn_module_conservation_flora_exsitu*"]
namespaces = true

[tool.setuptools.package-data]
"gn_module_conservation_flora_exsitu.migrations.data" = ["*.sql", "*.csv"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["backend"]

[tool.distutils.bdist_wheel]
universal = true

[tool.ruff]
# Maximum allowed line length
line-length = 100
# Target Python version
target-version = "py39"

[tool.ruff.lint]
# E et W : pycodestyle (PEP8)
# F : Pyflakes
# I : iSort
# B: flake8-bugbear (potential bugs)
# C90: flake8-mccabe (complexity)
# PL: Pylint (wide range of checks)
# PT: flake8-pytest-style (pytest best practices)
# SIM: flake8-simplify (simplification suggestions)
# T20: flake8-print (disallows `print` statements)
# RUF: Ruff-specific rules (fast and useful)
select = ["E", "W", "F", "I", "B", "C90", "PL", "PT", "SIM", "T20", "RUF"]
ignore = [
    "D100", # missing-module-docstring
    "D101", # missing-class-docstring
    "D102", # missing-function-or-method-docstring"
    "D107", # missing-docstring-in-init
]

[tool.ruff.format]
# Format code like Black
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
